"""Constants for ClimateSync integration."""

DOMAIN = "climatesync"

CONF_SOURCE_ENTITIES = "source_entities"
CONF_DESTINATION_ENTITY = "destination_entity"
CONF_DESTINATION_TARGET = "destination_target"
CONF_IDLE_TEMPERATURE = "idle_temperature"
CONF_MAX_SETPOINT = "max_setpoint"
CONF_ROUNDING_MODE = "rounding_mode"
CONF_ROUNDING_DIRECTION = "rounding_direction"
CONF_RESYNC_INTERVAL = "resync_interval_seconds"
CONF_MIN_CHANGE_THRESHOLD = "min_change_threshold"
CONF_MIN_SEND_INTERVAL = "min_send_interval_seconds"
CONF_DEMAND_ACTIVATION_THRESHOLD = "demand_activation_threshold"
CONF_DEMAND_DEACTIVATION_THRESHOLD = "demand_deactivation_threshold"

DEFAULT_IDLE_TEMPERATURE = 5.0
DEFAULT_MAX_SETPOINT = 35.0
DEFAULT_ROUNDING_MODE = "1_decimal"
DEFAULT_RESYNC_INTERVAL = 60
DEFAULT_MIN_CHANGE_THRESHOLD = 0.2
DEFAULT_MIN_SEND_INTERVAL = 10
DEFAULT_DEMAND_ACTIVATION_THRESHOLD = 0.3
DEFAULT_DEMAND_DEACTIVATION_THRESHOLD = 0.1

DESTINATION_TARGET_TEMPERATURE = "temperature"
DESTINATION_TARGET_LOW = "target_temp_low"
DESTINATION_TARGET_HIGH = "target_temp_high"
DESTINATION_TARGETS = (
    DESTINATION_TARGET_TEMPERATURE,
    DESTINATION_TARGET_LOW,
)
DEFAULT_DESTINATION_TARGET = DESTINATION_TARGET_TEMPERATURE

ROUNDING_MODE_HALF = "half_step"
ROUNDING_MODE_1DEC = "1_decimal"
ROUNDING_MODE_2DEC = "2_decimals"

ROUNDING_MODES = (ROUNDING_MODE_HALF, ROUNDING_MODE_1DEC, ROUNDING_MODE_2DEC)

ROUNDING_DIRECTION_FLOOR = "floor"
ROUNDING_DIRECTION_NEAREST = "nearest"
ROUNDING_DIRECTION_CEILING = "ceiling"

ROUNDING_DIRECTIONS = (
    ROUNDING_DIRECTION_FLOOR,
    ROUNDING_DIRECTION_NEAREST,
    ROUNDING_DIRECTION_CEILING,
)

DEFAULT_ROUNDING_DIRECTION = ROUNDING_DIRECTION_NEAREST

# Status states for sensor.climatesync_status
STATUS_OK = "ok"
STATUS_RATE_LIMITED = "rate_limited"
STATUS_DESTINATION_UNAVAILABLE = "destination_unavailable"
STATUS_MISSING_SOURCE_DATA = "missing_source_data"
STATUS_DEGRADED_SOURCE_DATA = "degraded_source_data"
STATUS_APPLY_FAILED = "apply_failed"
STATUS_MISMATCH = "mismatch"
